apiVersion: v1
kind: Service
metadata:
  name: apiiro-dvd
spec:
  selector:
    app: apiiro-dvd
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiiro-dvd
  labels:
    app: apiiro-dvd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiiro-dvd
  template:
    metadata:
      labels:
        app: apiiro-dvd
    spec:
      containers:
        - name: apiiro-dvd
          image: gcr.io/apiiro/tools/dvd:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
